module(name = "axlearn", version = "0.0.1")

# BEGIN_APPLE
bazel_dep(name = "apple_federation", version = "0.212.0")
# END_APPLE

bazel_dep(name = "rules_python", version = "1.5.3")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.12")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(hub_name = "pip", python_version = "3.12", requirements_lock = "//:requirements_lock.txt")
use_repo(pip, "pip")
