load("//pytype_bazel:pytype.bzl", "pytype_library")

pytype_library(
    name = "utils",
    srcs = ["utils.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "bastion",
    srcs = ["bastion.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "bundler",
    srcs = ["bundler.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "quota",
    srcs = ["quota.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "scheduler",
    srcs = ["scheduler.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "types",
    srcs = ["types.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)
