load("//pytype_bazel:pytype.bzl", "pytype_library")

pytype_library(
    name = "base",
    srcs = ["base.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)
