load("//pytype_bazel:pytype.bzl", "pytype_library")

# TODO(wyi): Consider rename __init__.py into root_module.py
pytype_library(
    name = "cloud",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)
