load("//pytype_bazel:pytype.bzl", "pytype_library")

pytype_library(
    name = "launch_utils",
    srcs = ["launch_utils.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)

pytype_library(
    name = "bastion_vm",
    srcs = ["bastion_vm.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@axlearn_pip//absl_py",
    ],
)
